### ISSUE TITLE
Wizard To-Do List

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling-cli#57]
This is a list of known issues/things to improve in the Wizard. As of current writing (Oct 2021), I'm working on the things listed as "before release of v0.3." For things listed as "after v0.3", I'd happily accept PRs!

#### Before release of v0.3

- [x] Add help for `n_frames_max` ([#58](https://github.com/openpathsampling/openpathsampling-cli/pull/58))
- [x] Add help for volume category ([#58](https://github.com/openpathsampling/openpathsampling-cli/pull/58))
- [x] Add help for Union, Intersection, and Complement volumes ([#58](https://github.com/openpathsampling/openpathsampling-cli/pull/58))
- [x] Add LoadFromOPSFile to volumes ([#58](https://github.com/openpathsampling/openpathsampling-cli/pull/58))
- [x] Use `Helper` to parse input when selecting objects from OPS file (allow commands) ([#58](https://github.com/openpathsampling/openpathsampling-cli/pull/58))
- [x] Add support for catching the quit exception when the wizard is running ([#63](https://github.com/openpathsampling/openpathsampling-cli/pull/63))
- [x] Ensure that plugin load order is preserved (create an `OrderedSet` to handle this) ([#60](https://github.com/openpathsampling/openpathsampling-cli/pull/60))
- [x] Add pauses at various points to give better UX ([#62](https://github.com/openpathsampling/openpathsampling-cli/pull/62))
  * creating subvolumes
  * after naming an object
 - [ ] Write wizard usage docs (probably in core OPS)
 - [x] flake8/pylint pass over wizard subdirectory ([#66](https://github.com/openpathsampling/openpathsampling-cli/pull/66))

#### After v0.3

- [ ] Fix error when bad filename given while loading topology from PDB (should give file not found error):

  ```
  🧙 Where is a PDB file describing your system? foo.pdb
  
  👺 Sorry, I couldn't understand the input 'foo.pdb'.
     Here's the error I got:
     RuntimeError: No CategoryCompiler registered for 'engine'
  ```
- [ ] Add `??` functionality to get help about help (what additional options are allowed for help -- e.g., for category help, you can give either number or name)
- [ ] Add `?repeat` (and `!repeat`, perhaps?) to repeat a question -- especially in the case of `ask_enumerate_dict` type of things.
- [ ] Add `!ls` command (should this call the system version to match user prefs on output (color, etc)?)
- [ ] Enable history with up-arrow (should be at the level of the `console`, see Python stdlib module `readline`)
- [ ] Add help when selecting from existing objects (must come from `context`, I think)
- [ ] Remove `ask_enumerate`, replace all with `ask_enumerate_dict`
- [ ] Add summary for after using LoadFromOPSFile (it feels too abrupt going to the next thing now)

... and, obviously, add we need to extend support to add more options from the tools in OPS!
